CREATE TABLE IF NOT EXISTS USER(
    UId INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    phone VARCHAR(13) NOT NULL,
    type VARCHAR(10) NOT NULL,
    user_id VARCHAR(15) NOT NULL,
    password VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UId)
);
CREATE TABLE IF NOT EXISTS FREELANCER(
    FId INT NOT NULL AUTO_INCREMENT,
    UId INT NOT NULL,
    major VARCHAR(10) NOT NULL,
    period INT NOT NULL,
    external_portfolio VARCHAR(100) NOT NULL,
    PRIMARY KEY(FId),
    FOREIGN KEY(UId) REFERENCES USER(UId)
);
CREATE TABLE IF NOT EXISTS CLIENT(
    CId INT NOT NULL AUTO_INCREMENT,
    UId INT NOT NULL,
    PRIMARY KEY(CId),
    FOREIGN KEY(UId) REFERENCES USER(UId)
);
CREATE TABLE IF NOT EXISTS FREELANCER_LANGUAGE(
    FId INT NOT NULL,
    language VARCHAR(20) NOT NULL,
    level INT NOT NULL,
    PRIMARY KEY(FId, language)
);
CREATE TABLE IF NOT EXISTS PROJECT(
    PId INT NOT NULL AUTO_INCREMENT,
    CId INT NOT NULL,
    cost INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    min_career INT NOT NULL,
    status VARCHAR(20),
    min_members INT NOT NULL,
    max_members INT NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(PId),
    FOREIGN KEY(CId) REFERENCES CLIENT(CId)
);
CREATE TABLE IF NOT EXISTS PROJECT_REQUEST_DOC(
    DId INT NOT NULL AUTO_INCREMENT,
    PId INT NOT NULL,
    URL VARCHAR(100) NOT NULL,
    PRIMARY KEY(DId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId)
);
CREATE TABLE IF NOT EXISTS PROJECT_RESULT_REPORT(
    RId INT NOT NULL AUTO_INCREMENT,
    PId INT NOT NULL,
    URL VARCHAR(100) NOT NULL,
    is_rejected BOOLEAN NOT NULL,
    create_date DATE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(RId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId)
);
CREATE TABLE IF NOT EXISTS PROJECT_COMPLETE_REJECT_MESSAGE(
    MId INT NOT NULL AUTO_INCREMENT,
    PId INT NOT NULL,
    message VARCHAR(500) NOT NULL,
    create_date DATE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(MId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId)
);
CREATE TABLE IF NOT EXISTS PROJECT_LANGUAGE(
    PId INT NOT NULL,
    language VARCHAR(20) NOT NULL,
    level INT NOT NULL,
    PRIMARY KEY(PId, language),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId)
);
CREATE TABLE IF NOT EXISTS TEAM(
    TId INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    leader INT NOT NULL,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY(TId),
    FOREIGN KEY(leader) REFERENCES FREELANCER(FId)
);
CREATE TABLE IF NOT EXISTS TEAM_MEMBER(
    TId INT NOT NULL,
    FId INT NOT NULL,
    PRIMARY KEY(TId, FId),
    FOREIGN KEY(TId) REFERENCES TEAM(TId),
    FOREIGN KEY(FId) REFERENCES FREELANCER(FId)
);
CREATE TABLE IF NOT EXISTS REQUEST(
    RId INT NOT NULL AUTO_INCREMENT,
    PId INT NOT NULL,
    TId INT NOT NULL,
    is_accepted BOOLEAN NOT NULL,
    create_date  DATE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(RId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId),
    FOREIGN KEY(TId) REFERENCES TEAM(TId)
);
CREATE TABLE IF NOT EXISTS FREELANCER_RATE(
    PId INT NOT NULL,
    FId INT NOT NULL,
    rate INT NOT NULL,
    PRIMARY KEY(PId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId),
    FOREIGN KEY(FId) REFERENCES FREELANCER(FId)
);
CREATE TABLE IF NOT EXISTS CLIENT_RATE(
    PId INT NOT NULL,
    CId INT NOT NULL,
    rate INT NOT NULL,
    PRIMARY KEY(PId),
    FOREIGN KEY(PId) REFERENCES PROJECT(PId),
    FOREIGN KEY(CId) REFERENCES CLIENT(CId)
);